# Generated by Django 4.0.2 on 2022-02-19 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('complete', models.CharField(choices=[('complete', 'complete'), ('uncomplete', 'uncomplete')], default='uncomplete', max_length=20)),
                ('grouping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todos.grouping')),
            ],
        ),
    ]
